Fix Windows build, where sal_Int32 is not int
 C:/lo/core/editeng/qa/unit/core-test.cxx(2390): error C2668: 'EditDoc::GetParaAsString': ambiguous call to overloaded function
 C:\lo\core\editeng\inc\editdoc.hxx(195): note: could be 'rtl::OUString EditDoc::GetParaAsString(const ContentNode *,sal_Int32,sal_Int32)'
 C:\lo\core\editeng\inc\editdoc.hxx(194): note: or       'rtl::OUString EditDoc::GetParaAsString(sal_Int32) const'
 C:/lo/core/editeng/qa/unit/core-test.cxx(2390): note: while trying to match the argument list '(int)'
 C:/lo/core/editeng/qa/unit/core-test.cxx(2413): error C2668: 'EditDoc::GetParaAsString': ambiguous call to overloaded function
 C:\lo\core\editeng\inc\editdoc.hxx(195): note: could be 'rtl::OUString EditDoc::GetParaAsString(const ContentNode *,sal_Int32,sal_Int32)'
 C:\lo\core\editeng\inc\editdoc.hxx(194): note: or       'rtl::OUString EditDoc::GetParaAsString(sal_Int32) const'
 C:/lo/core/editeng/qa/unit/core-test.cxx(2413): note: while trying to match the argument list '(int)'

Instead of using an explicit GetParaAsString(sal_Int(0)) just for 0,
adjacent to GetParaAsString(1), which creates inconsistency, this
change introduces a templated overload to disambiguate.

Change-Id: Ib22680b7bfb591e436ebc323f6ef25699c26b1ec
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/201629
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>