python3: fix build on Linux where /usr/include/ncurses.h is broken
If --with-python=internal is used, then building its curses module
expects an ncurses header with wide char support, otherwise the build
fails with:

	/usr/bin/ccache clang -fsanitize=address -fsanitize=undefined -fsanitize=float-divide-by-zero -fsanitize=local-bounds -fsanitize-blacklist=sanitize-ubsan-excludelist -fno-sanitize=function -Iworkdir/UnpackedTarball/bzip2 -Iworkdir/UnpackedTarball/expat/lib -Iworkdir/UnpackedTarball/sqlite3 -Iworkdir/UnpackedTarball/lzma/src/liblzma/api  -fno-strict-overflow -Wsign-compare -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -Og -Wall -Iworkdir/UnpackedTarball/zlib -O0 -Wp,-U_FORTIFY_SOURCE -fstrict-aliasing -fstrict-overflow   -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal  -I. -I./Include   -fPIC -fPIC -c ./Modules/_cursesmodule.c -o Modules/_cursesmodule.o
	./Modules/_cursesmodule.c:764:9: error: call to undeclared function 'setcchar'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
	  764 |         setcchar(&wcval, wstr, attr, PAIR_NUMBER(attr), NULL);
	      |         ^

Turns out that /usr/include/ncurses.h and
/usr/include/ncursesw/ncurses.h are not the same here and only the later
provides the wide char support.

Fix this by explicitly adding /usr/include/ncursesw to the include path
on Linux, which should help when that dir exists and it's meant to be
ignored otherwise.

Change-Id: Ic967163d4dbab5df6a0c95146f0d92b564c9901c
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/201812
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>